name: Run Tests

permissions:
    contents: read

on:
    pull_request:
        branches:
        - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Install Node
              uses: actions/setup-node@v6
              with:
                node-version: '22'

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Install dependencies
              working-directory: ./src
              run: pnpm install

            - name: Test with tsc
              working-directory: ./src
              run: npx tsc --noEmit

    build-docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Build Docker image
              run: docker build . -t ghcr.io/wg-easy/wg-easy:latest